server:
  # 开启响应数据压缩、默认只压缩超过2048 字节的数据
  compression:
    enabled: false
    mime-types: application/json
  port: 8732

spring:
  profiles:
    # maven???profile????local
    active: @profileActive@
  application:
    name: Easy-SpringBoot-CLI
  datasource:
    url: jdbc:mysql://localhost:3306/easy_cli?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    druid:
      db-type: mysql
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  #rabbitmq配置
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: user
#    password: admin
  jackson:
    # 序列化时间格式 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  global-config:
    # 逻辑删除配置
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDel
api-enc:
  # 是否开启请求加密
  requestEnable: true
  # 是否开启响应加密
  respondEnable: true
  # 请求头中携带的加密字段 AES 密钥加密后密文
  keyHeader: Encrypt-Key
  # RSA加解密密钥
  publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMrHKwbWS2BhsReRcDsCrt+Q4J1GIgWdk8t9+3SlD+Dq8D+C8bmeeRNEqzXKEBeRp9urWMwu5HRLBC1J1U1K38sCAwEAAQ==
  privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAyscrBtZLYGGxF5FwOwKu35DgnUYiBZ2Ty337dKUP4OrwP4LxuZ55E0SrNcoQF5Gn26tYzC7kdEsELUnVTUrfywIDAQABAkAggbEqFWxb9Q04o/4D17hE6qq3S6jkkZBBzN5koplbCsVxJrxHmVT44FUc82F2SYu7jSGtBqwlfc6Ij4arGfIBAiEA8VPo7y/MAH0hVVHvuP0FaNIoNpRHBzdmmB01lR/PoIECIQDXG0JZ6Q7Wr9Z7bsgaiQ1XnwHcbWg/+BS3ivwlaEnaSwIgZoTwApR6hIaj33wEa8DJSINm4/DPz8gARIS8G5K9AIECIQCEJgT/Q4SQM/pqXkaktqnxuIfmKXiwQ/JGSCZbvNQSPQIgBTwnFxLPAafFYUtDooVS+tT2O/XAP7QkvCc0XmK6gGQ=